@host = localhost:5139

###
GET http://{{host}}/api/insight
X-Requested-With: XMLHttpRequest

###
GET http://{{host}}/api/transaction
X-Requested-With: XMLHttpRequest

###
POST http://{{host}}/api/transaction/generate?count=10000
X-Requested-With: XMLHttpRequest

###
POST http://{{host}}/api/transaction
Content-Type: application/json

{
  "value": 100,
  "date": "2025-05-02T10:00:00Z",
  "category": "Food",
  "transactionDetails": [
    {
      "value": 60,
      "description": "Groceries",
      "quantity": 1,
      "category": "Groceries"
    },
    {
      "value": 40,
      "description": "Snacks",
      "quantity": 1,
      "category": "Snacks"
    }
  ]
}

###
PUT http://{{host}}/api/transaction/1
Content-Type: application/json

{
  "id": 1,
  "value": 300,
  "date": "2025-05-02T14:00:00Z",
  "category": "Utilities",
  "transactionDetails": []
}
