@host = localhost:5139
@apikey = 5hjW2TrjpgAEU9j78qt7ri78H88vuLrCZQrbMGCIVoo

###
GET http://{{host}}/api/v1/monthlyreport
X-Requested-With: XMLHttpRequest
X-Api-Key: {{apikey}}

###
GET http://{{host}}/api/v1/backup
X-Requested-With: XMLHttpRequest
X-Api-Key: {{apikey}}
