@host = localhost:5139

###
GET http://{{host}}/api/transaction
X-Requested-With: XMLHttpRequest

###
GET http://{{host}}/api/insight
X-Requested-With: XMLHttpRequest

###
GET http://{{host}}/api/insight/history
X-Requested-With: XMLHttpRequest
