name: Build and Publish Ledger Eleven Images

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag name
        id: get_tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            TAG="latest"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push auth-server image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./.devops/build/Dockerfile.ledger-eleven-auth-server
          push: true
          tags: |
            ghcr.io/xlansoftware/ledger-eleven-auth-server:latest
            ghcr.io/xlansoftware/ledger-eleven-auth-server:${{ steps.get_tag.outputs.tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build and push app image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./.devops/build/Dockerfile.ledger-eleven-app
          push: true
          tags: |
            ghcr.io/xlansoftware/ledger-eleven-app:latest
            ghcr.io/xlansoftware/ledger-eleven-app:${{ steps.get_tag.outputs.tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
