name: Test frontend

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - main

permissions:
  contents: read
  actions: read
  checks: write
      
jobs:
  test:
    name: Run Web Tests
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make script executable
        working-directory: ./.devops/test/web/certs
        run: chmod +x generate-test-certificates.sh

      - name: Generate self-host certificates
        working-directory: ./.devops/test/web/certs
        run: ./generate-test-certificates.sh

      - name: Build and test
        working-directory: ./.devops/test/web
        run: docker compose run --build --rm test

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Test results
          path: ./.devops/test/web/test-results/
      
