name: Test backend

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  checks: write
      
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and test
        working-directory: ./.devops/test/backend
        run: docker compose run --build --rm app-test

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: .NET Tests
          path: ./.devops/test/backend/test-results/test-results.trx
      
